services:
  - type: web
    name: jobguard-api
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && python python_models/train_models.py"
    startCommand: "gunicorn --chdir flask_backend app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
