services:
  - type: web
    name: jobguard-api
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements_enhanced.txt && python python_models/train_models.py"
    startCommand: "gunicorn --chdir flask_backend app_enhanced:app --bind 0.0.0.0:$PORT --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTORCH_ENABLE_MPS_FALLBACK
        value: "1"
